### ISSUE TITLE
doctrine:fixtures does not work in APP_ENV=prod

### ISSUE THREAD

**Issue by hahnjo** [ClusterCockpit/ClusterCockpit#26]
AFAICS the commands are only available with `APP_ENV=dev`. This is unfortunate because this doesn't work for production environments with `APP_ENV=prod`.

**Comment by moebiusband73** [comment]
This is intended.

I will document this explicitly. This is because the relevant functionality is only installed if in dev mode.
Once a database is used in production you should NEVER load fixtures as they will wipe out the database.

The workflow is to set everything up in dev mode and when everything works switch to production  mode. Once in production you should only sync using sql dumps.

**Comment by moebiusband73** [comment]
I introduced a dedicated console command app:init that initializes the database and creates an admin user. The solution based on doctrine:fixtures is not used anymore.

The app:init command is available in all environments and also there is no danger to purge an existing database. 

Thanks for your input.
